### ISSUE TITLE
I am keen to join your team and utilize my expertise to help achieve outstanding results on your projects.

### ISSUE THREAD

**Issue by 0x0factor** [laboratorybyopsa/laboratory#1]
Hello, I'm Ethan Tan, a veteran web full-stack and blockchain developer with over 8 years of experience. I excel in creating scalable, high-performance web applications and pioneering blockchain solutions. With expertise in frameworks like React.js, Vue.js, and Next.js, and a strong command of Solidity for smart contract development, I deliver top-tier, secure, and efficient solutions customized to your requirements.

**Comment by A6rron** [comment]
hey dude, we are in ideation stage so we are broke af, cant afford to pay. if you want to join in as a core contributor you are always welcome

**Comment by 0x0factor** [comment]
okay I got it
